### ISSUE TITLE
0x6603981C104b13B77316AD23285A0AE918Ef4400

### ISSUE THREAD

**Issue by QianMeng66** [Project-DARC/DARC#114]
### Discussed in https://github.com/orgs/Project-DARC/discussions/110

<div type='discussions-op-text'>

<sup>Originally posted by **lidangzzz** March 23, 2024</sup>
1. 给 [https://github.com/Project-DARC/DARC](https://github.com/Project-DARC/DARC) 点star+fork+watch，一键三连（不要在这个代码库里添加issue，切记，否则会被社区永久拉黑）；

2. 在本帖下面留下你的以太坊地址。

兄弟们，开始。</div>

**Comment by BackserEcation** [comment]
0x17AEA261400324EC8bD78580A3884ed193fa98aD
