### ISSUE TITLE
https://darc.app/  无法访问 

### ISSUE THREAD

**Issue by hubei2023** [Project-DARC/DARC#24]

**Comment by Gxjx2017** [comment]
没搞懂

**Comment by wenyuxi146** [comment]
??

**Comment by ASheng-0210** [comment]
您发送的邮件已收到，我会尽快处理，谢谢！ Your email has been received, I will deal with as soon as possible, thank you!

**Comment by ryanhhh123** [comment]
这傻逼邮件怎么退订啊

ASheng-0210 ***@***.***>于2023年12月22日 周五18:17写道：

**Comment by jq369** [comment]
煞笔邮件cnmd

**Comment by AGDholo** [comment]
已修复

**Comment by ASheng-0210** [comment]
您发送的邮件已收到，我会尽快处理，谢谢！ Your email has been received, I will deal with as soon as possible, thank you!
