### ISSUE TITLE
mint

### ISSUE THREAD

**Issue by qi807959951** [Project-DARC/DARC#31]
{
  "p": "GRC20", 
  "op": "mint", 
  "tick": "GitHub", 
  "amt": "2000"
}

**Comment by AgentLex** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by lai550b** [comment]
开始打铭文了吗？教我怎么做





------------------ Original ------------------
From: AgentLex ***@***.***&gt;
Date: Sat,Dec 30,2023 0:32 PM
To: Project-DARC/DARC ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [Project-DARC/DARC] mint (Issue #31)





 
{
 "p": "GRC20",
 "op": "mint",
 "tick": "GitHub",
 "amt": "2000"
 }
