### ISSUE TITLE
Mint

### ISSUE THREAD

**Issue by abirprox** [Project-DARC/DARC#35]
{  
  "p": "GRC20", 
  "op": "mint", 
  "tick": "GitHub", 
  "amt": "2000"
}

**Comment by fengmao** [comment]
{ 
  "p": "GRC20",
  "op": "mint",
  "tick": "GitHub",
  "amt": "2000"
}

**Comment by Levvercetti** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by xuan1013-dev** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by hermanwang** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Project-DARC/DARC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月30日(星期六) 凌晨0:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Project-DARC/DARC] Mint (Issue #35)





 
{
 "p": "GRC20",
 "op": "mint",
 "tick": "GitHub",
 "amt": "2000"
 }

**Comment by a18851932** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by distoken001** [comment]
{"p": "GRC20","op": "mint","tick": "GitHub","amt": "2000"}在 2023年12月30日，00:07，xuan1013-dev ***@***.***> 写道：﻿
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by curtis0815** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by r1cher** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by snjyor** [comment]
{"p":"GRC20","op": "mint","tick": "GitHub","amt":"2000"}

**Comment by snjyor** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by snjyor** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by wangliusen** [comment]
你搁这mint你妈呢



发自我的iPhone


------------------ Original ------------------
From: Jeffrey Yang ***@***.***&gt;
Date: Sat,Dec 30,2023 3:17 PM
To: Project-DARC/DARC ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [Project-DARC/DARC] Mint (Issue #35)





 
{"p":"GRC20","op": "mint","tick": "GitHub","amt":"2000"}
