### ISSUE TITLE
Mint

### ISSUE THREAD

**Issue by fengmao** [Project-DARC/DARC#36]
{ 
  "p": "GRC20",
  "op": "mint",
  "tick": "GitHub",
  "amt": "2000"
}

**Comment by modewei** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by a18851932** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by minwiki7456** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by minwiki7456** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by Lh104621** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by cao527359912** [comment]
煞笔 别发了



发自我的iPhone


------------------ Original ------------------
From: Lh104621 ***@***.***&gt;
Date: Sat,Dec 30,2023 3:33 PM
To: Project-DARC/DARC ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [Project-DARC/DARC] Mint (Issue #36)
