### ISSUE TITLE
mint

### ISSUE THREAD

**Issue by garenacso** [Project-DARC/DARC#83]
{  
  "p": "GRC20", 
  "op": "mint", 
  "tick": "GitHub", 
  "amt": "2000"
}

**Comment by kaweh** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by whatever3721** [comment]
{
"p": "GRC20",
"op": "mint",
"tick": "GitHub",
"amt": "2000"
}

**Comment by vvck001** [comment]
怎么关闭这个邮件，一直发，好烦啊


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Project-DARC/DARC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月1日(星期一) 下午5:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Project-DARC/DARC] mint (Issue #83)





 
Closed #83 as completed.

**Comment by erwa667** [comment]
好好吧

阿克顿将 ***@***.***>于2024年1月3日 周三14:53写道：
